Repository jrnl-org/jrnl, pull requests merged in 2019-10, with the labels that each got.

#418 Add exporter to output entries inside unicode box character boxes
  jrnl/plugins/__init__.py
  jrnl/plugins/fancy_exporter.py
Labels: enhancement

#665 Fixes Issue #662 - Day names not treated consistently for new entry
  features/regression.feature
  features/steps/core.py
  jrnl/Journal.py
  jrnl/time.py
Labels: bug

#458 Issue #170 - Add folder based journal
  features/data/journals/empty_folder/empty
  features/folder.feature
  features/steps/core.py
  jrnl/FolderJournal.py
  jrnl/Journal.py
Labels: enhancement

#679 Create templates for issues and pull requests
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Support_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: :star:, documentation
