Repository jrnl-org/jrnl, pull requests merged in 2019-11, with the labels that each got.

#694 Fix parsing Journals using a little-endian date format
  features/custom_dates.feature
  features/data/configs/little_endian_dates.yaml
  features/data/configs/upgrade_from_195_little_endian_dates.json
  features/data/journals/little_endian_dates.journal
  features/data/journals/simple_jrnl-1-9-5_little_endian_dates.journal
  features/upgrade.feature
  jrnl/Journal.py
Labels: :star:, bug

#699 Fix crash when no keyring backend available
  jrnl/util.py
Labels: bug

#742 [Dayone] re-add tests
  features/dayone.feature
  features/dayone_regressions.feature
  features/environment.py
Labels: day one

#752 [GH-693] Updating developer documentation (work in progress)
  CONTRIBUTING.md
Labels: documentation, help wanted

#751 [GH-738] preventing readline usage on Windows
  jrnl/install.py
Labels: bug, windows

#759 More Travis-CI Testing
  .travis.yml
  features/steps/core.py
  pyproject.toml
Labels: enhancement

#763 Display header in docs on mobile devices
  docs/assets/theme.css
Labels: documentation
