Repository jrnl-org/jrnl, pull requests merged in 2019-08, with the labels that each got.

#612 Use Poetry for dependency management and deployments
  .gitignore
  .travis.yml
  MANIFEST.in
  Makefile
  jrnl/__init__.py
  poetry.lock
  pyproject.toml
  setup.py
Labels: :star:, enhancement

#633 Add recipe to display random entry
  docs/recipes.md
Labels: documentation

#639 Switch to hashmark Markdown headers on export (Mk II)
  features/exporting.feature
  jrnl/plugins/markdown_exporter.py
  jrnl/plugins/yaml_exporter.py
Labels: enhancement

#492 In Encryption docs, explain how to prevent Fish history logging
  docs/encryption.md
Labels: documentation

#649 Smaller doc fixes
  README.md
  docs/advanced.md
  docs/overview.md
  docs/recipes.md
  docs/usage.md
Labels: documentation

#650 [GH-632] confirming that each journal can be parsed during upgrade
  features/encryption.feature
  features/regression.feature
  features/upgrade.feature
  jrnl/Journal.py
  jrnl/install.py
  jrnl/upgrade.py
Labels: bug
