Repository jrnl-org/jrnl, pull requests merged in 2019-09, with the labels that each got.

#550 Handle KeyboardInterrupt when installing journal
  jrnl/cli.py
  jrnl/install.py
  jrnl/upgrade.py
  jrnl/util.py
Labels: :star:, enhancement

#637 Add '-not' flag for excluding tags from filter
  features/tagging.feature
  jrnl/Journal.py
  jrnl/cli.py
Labels: enhancement

#655 Fix references to Sphinx in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#660 Change pyYAML required version
  setup.py
Labels: bug
