Repository jrnl-org/jrnl, pull requests merged in 2020-05, with the labels that each got.

#934 Disable --delete due to critical bug
  features/delete.feature
  jrnl/cli.py
Labels: bug

#937 Allow most recent pytz version and update dependencies
  poetry.lock
  pyproject.toml
Labels: enhancement

#936 Change jrnl.sh GitHub new issue link to issue template chooser
  docs/theme/index.html
Labels: documentation

#935 Prevent filtered delete from deleting journal
  features/data/configs/deletion_filters.yaml
  features/data/journals/deletion_filters.journal
  features/delete.feature
  features/steps/core.py
  jrnl/Journal.py
  jrnl/cli.py
Labels: bug

#940 Make sure testing cleans up after itself
  features/environment.py
  features/exporting.feature
  features/regression.feature
  features/steps/core.py
  features/steps/export_steps.py
Labels: build

#925 Improve privacy, security, and encryption documentation #896
  docs/encryption.md
  docs/security.md
  mkdocs.yml
Labels: documentation

#947 Use gitlab to trigger releases in pipeline
  .build/generate_changelog.sh
  .build/gitlab-ci.yml
  .travis.yml
Labels: build

#951 Ask for password before adding entry instead of after
  jrnl/cli.py
Labels: bug

#941 Update lockbot comment to encourage linking to issue
  .github/lock.yml
Labels: build

#953 Fix editor config when an argument with a space is used
  features/core.feature
  features/data/configs/editor-args.yaml
  features/steps/core.py
  jrnl/cli.py
  jrnl/util.py
Labels: bug

#956 Cleaned up usage.md for clarity, formatting, and grammar.
  docs/usage.md
Labels: documentation

#965 Ensure test data is always checked out with LF line endings
  .gitattributes
Labels: build, windows

#959 Speed up jrnl by 10%, improve slow imports
  jrnl/cli.py
  jrnl/install.py
  jrnl/time.py
  jrnl/upgrade.py
  jrnl/util.py
Labels: enhancement

#958 Fix title splitting logic to account for both newlines and periods
  features/core.feature
  jrnl/util.py
Labels: bug

#969 Fix for hanging Windows tests on Travis
  features/core.feature
  features/steps/core.py
Labels: build
