Repository jrnl-org/jrnl, pull requests merged in 2020-08, with the labels that each got.

#1016 Resolve Travis/Windows/pip issues with upgrade to cryptography 3.0
  .travis.yml
  poetry.lock
  pyproject.toml
Labels: build, windows

#1023 Updated advanced.md in docs to reflect all four subkeys under colors …
  docs/advanced.md
Labels: documentation

#1022 Update github issue templates to use new diagnostic command
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/support_request.md
Labels: documentation

#1018 Add support for Python 3.9 build testing
  .build/allow_all_python_version.py
  .travis.yml
Labels: build
