Repository jrnl-org/jrnl, pull requests merged in 2020-11, with the labels that each got.

#1070 Add mac tests to Circle CI config
  .circleci/config.yml
Labels: build

#1082 get rid of travis and circle configs (in favor of github actions)
  .build/gitlab-ci.yml
  .circleci/config.yml
  .circleci/pa11y.sh
  .travis.yml
Labels: build

#1086 Add changelog generation workflow to github actions
  .build/generate_changelog.sh
  .github/workflows/changelog.yaml
  .github_changelog_generator
Labels: build

#1091 Add ability to put --edit partly through a cli entry to move it to the editor
  features/steps/core.py
  features/write.feature
  jrnl/jrnl.py
Labels: enhancement

#1090 Fix Unicode encoding failure in directory export when creating filenames from journal titles with certain characters
  features/format.feature
  jrnl/plugins/text_exporter.py
Labels: bug

#1094 Udpate build badge in readme to point at github instead of travis
  README.md
Labels: build

#1095 Add a release workflow for PyPI in CI (Github Actions)
  .github/workflows/changelog.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/testing.yaml
Labels: build

#1101 Add fix for changelog conditional always returning false
  .github/workflows/changelog.yaml
Labels: build
