Repository jrnl-org/jrnl, pull requests merged in 2020-01, with the labels that each got.

#806 Automagically update the changelog you see before your very eyes!
  .build/generate_changelog.sh
  .github_changelog_generator
  .travis.yml
Labels: build

#807 Change PyPI auth method in build pipeline
  .travis.yml
Labels: build

#792 Close temp file before passing it to editor to prevent file locking issues in Windows
  jrnl/util.py
Labels: bug

#809 Explain how fish can be configured to exclude jrnl commands from history by default
  docs/encryption.md
Labels: documentation

#789 Fix crash while encrypting a journal on first run without saving password
  jrnl/util.py
Labels: bug

#808 Unpin poetry
  .travis.yml
Labels: build

#823 Fix all skipped tests on Travis Windows builds by preserving newlines
  .travis.yml
  features/dayone_regressions.feature
  features/encryption.feature
  features/upgrade.feature
Labels: build
