Repository jrnl-org/jrnl, pull requests merged in 2020-12, with the labels that each got.

#1104 Check for readline module instead of Windows when initializing autocomplete in install
  jrnl/install.py
  tests/test_install.py
Labels: bug

#1105 Make docs site (jrnl.sh) fully meet Web Content Accessibility Guidelines (WCAG) 2.1
  .github/workflows/docs.yaml
  .github/workflows/pa11y.sh
  docs/assets/highlight.css
  docs/assets/theme.css
  docs/formats.md
  docs/installation.md
  docs/theme/img/sprites.svg
  docs/theme/index.css
  docs/usage.md
  docs_theme/CNAME
  docs_theme/assets/colors.css
  docs_theme/assets/highlight.css
  docs_theme/assets/index.css
  docs_theme/assets/readme-header.png
  docs_theme/assets/theme.css
  docs_theme/img/banner_og.png
  docs_theme/img/banner_twitter.png
  docs_theme/img/favicon.ico
  docs_theme/img/favicon.svg
  docs_theme/img/jrnl_white.svg
  docs_theme/img/logo.svg
  docs_theme/img/logo_white.svg
  docs_theme/img/sprites.svg
  docs_theme/index.html
  docs_theme/index.js
  docs_theme/main.html
  docs_theme/requirements.txt
  mkdocs.yml
  readthedocs.yml
Labels: documentation

#1110 Update all dependencies and lock file
  poetry.lock
  pyproject.toml
Labels: build

#1117 Typo fix in output.py: "us" -> "use"
  jrnl/output.py
Labels: bug

#1116 Change approach for docs workflow to use pa11y-ci
  .github/workflows/docs.yaml
Labels: build

#1114 Fix trigger for changelog
  .github/workflows/changelog.yaml
Labels: build

#1111 Add automatic deployment for homebrew releases (and prereleases)
  .github/workflows/release.yaml
Labels: build

#1122 Small accessibility fixes for docs site
  docs_theme/CNAME
  docs_theme/assets/colors.css
  docs_theme/assets/highlight.css
  docs_theme/assets/index.css
Labels: documentation

#1121 Comply with GPL by acknowledging all authors and including license info in each source file
  .github/workflows/testing.yaml
  CONTRIBUTING.md
  docs/advanced.md
  docs/encryption.md
  docs/formats.md
  docs/installation.md
  docs/overview.md
  docs/privacy-and-security.md
  docs/recipes.md
  docs/usage.md
  docs_theme/assets/colors.css
  docs_theme/assets/index.css
  docs_theme/assets/theme.css
  docs_theme/index.html
  features/core.feature
  features/steps/core.py
  features/steps/export_steps.py
  jrnl/Entry.py
  jrnl/FolderJournal.py
  jrnl/Journal.py
  jrnl/__init__.py
  jrnl/__main__.py
  jrnl/__version__.py
  jrnl/args.py
  jrnl/cli.py
  jrnl/commands.py
  jrnl/exception.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/os_compat.py
  jrnl/output.py
  jrnl/plugins/__init__.py
  jrnl/plugins/fancy_exporter.py
  jrnl/plugins/jrnl_importer.py
  jrnl/plugins/json_exporter.py
  jrnl/plugins/markdown_exporter.py
  jrnl/plugins/tag_exporter.py
  jrnl/plugins/template.py
  jrnl/plugins/template_exporter.py
  jrnl/plugins/text_exporter.py
  jrnl/plugins/util.py
  jrnl/plugins/xml_exporter.py
  jrnl/plugins/yaml_exporter.py
  jrnl/prompt.py
  jrnl/time.py
  jrnl/upgrade.py
  mkdocs.yml
  pyproject.toml
Labels: documentation

#1127 Fixes to changelog generator
  .github/workflows/changelog.yaml
Labels: build

#1126 Fix failing contrast test in accessibility tools on docs site
  docs_theme/assets/index.css
  docs_theme/assets/theme.css
Labels: documentation

#1132 Add packaging label to changelog generator config
  .github/workflows/changelog.yaml
Labels: documentation

#1133 Fix search on docs site
  docs_theme/main.html
Labels: documentation
