Repository jrnl-org/jrnl, pull requests merged in 2020-02, with the labels that each got.

#785 Add UTC support for failing DayOne tests
  features/dayone.feature
  jrnl/DayOneJournal.py
Labels: bug, day one

#786 Listing all entries in DayOne Classic journal throws IndexError
  .travis.yml
  features/data/configs/bug780.yaml
  features/data/journals/bug780.dayone/entries/48A25033B34047C591160A4480197D8B.doentry
  features/regression.feature
  jrnl/Entry.py
Labels: bug

#836 Fix crashing unicode Travis tests on Windows and fail build if Windows tests fail
  .travis.yml
Labels: build

#841 Update site description
  mkdocs.yml
Labels: documentation

#840 Get rid of dumb sex joke
  docs/usage.md
Labels: documentation

#839 Don't re-run tests on deployment
  .travis.yml
Labels: build

#838 Put back build lines in Poetry config
  pyproject.toml
Labels: build

#854 Docs: Fix broken links in recipes.md
  docs/recipes.md
Labels: documentation

#852 Fix configuration slashes and indentation in advanced usage documentation
  docs/advanced.md
Labels: documentation

#846 docs: Fix fish history instructions.
  docs/encryption.md
Labels: documentation

#843 Add support to save journals to multiple files in a directory
  features/data/journals/empty_folder/empty
  features/dayone_regressions.feature
  features/folder.feature
  features/steps/core.py
  jrnl/EncryptedJournal.py
  jrnl/FolderJournal.py
  jrnl/Journal.py
Labels: enhancement
