Repository jrnl-org/jrnl, pull requests merged in 2020-06, with the labels that each got.

#928 Add extended metadata support for DayOne Classic
  .gitignore
  CHANGELOG.md
  features/dayone.feature
  features/steps/export_steps.py
  jrnl/DayOneJournal.py
  jrnl/plugins/json_exporter.py
Labels: enhancement

#957 Extensive modifications to overview.md
  docs/overview.md
Labels: documentation

#972 Create journal with absolute path when no path is specified
  features/core.feature
  features/environment.py
  features/steps/core.py
  jrnl/install.py
Labels: bug

#975 Add tags to json and xml exporters
  features/exporting.feature
  features/steps/export_steps.py
  jrnl/plugins/json_exporter.py
  jrnl/plugins/xml_exporter.py
Labels: enhancement

#985 Rename master branch to release
  .build/generate_changelog.sh
  CONTRIBUTING.md
  README.md
Labels: build

#987 Add unit testing via pytest
  .travis.yml
  CONTRIBUTING.md
  Makefile
  poetry.lock
  pyproject.toml
  tests/test_time.py
Labels: build, test

#988 Make behave output more concise when running make test
  Makefile
Labels: test
