Repository jrnl-org/jrnl, pull requests merged in 2020-04, with the labels that each got.

#898 Update Poetry requirements for testing latest Python version
  .travis.yml
Labels: build

#904 Change install doc guideline from pip to pipx
  docs/installation.md
Labels: documentation

#909 Fix Python 3.9 incompatibility by updating plistlib
  jrnl/DayOneJournal.py
Labels: bug

#913 Update the code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#914 Update keyring version from "^19.0" to ">19.0, <22.0"
  poetry.lock
  pyproject.toml
Labels: enhancement

#908 Ensure exported entries end in a newline for Markdown and YAML exporters
  .gitignore
  features/regression.feature
  features/steps/export_steps.py
  jrnl/plugins/markdown_exporter.py
  jrnl/plugins/yaml_exporter.py
Labels: bug

#918 Upgrade license to GPLv3
  LICENSE
  LICENSE.md
  jrnl/cli.py
  pyproject.toml
Labels: enhancement

#919 Update makefile to match pipeline better
  Makefile
Labels: build

#923 Docs: editing config isn't always destructive
  docs/advanced.md
Labels: documentation

#924 Clean up readme file
  README.md
Labels: documentation
