Repository jrnl-org/jrnl, pull requests merged in 2020-10, with the labels that each got.

#1053 Disable logging by default
  jrnl/cli.py
Labels: bug

#1042 [WIP] Lots of test refactoring
  features/build.feature
  features/contains.feature
  features/core.feature
  features/custom_dates.feature
  features/data/configs/basic_dayone.yaml
  features/data/configs/basic_encrypted.yaml
  features/data/configs/basic_folder.yaml
  features/data/configs/basic_onefile.yaml
  features/data/configs/dayone_empty.yaml
  features/data/configs/editor_empty_folder.yaml
  features/data/configs/editor_encrypted.yaml
  features/data/configs/missing_directory.yaml
  features/data/configs/missing_journal.yaml
  features/data/configs/simple.yaml
  features/data/journals/basic_dayone.dayone/entries/D04D335AFED711EABA18FAFFC2100C3D.doentry
  features/data/journals/basic_dayone.dayone/entries/FC8A86CAFED711EA8892FAFFC2100C3D.doentry
  features/data/journals/basic_dayone.dayone/entries/FD8ABC8EFED711EABC35FAFFC2100C3D.doentry
  features/data/journals/basic_encrypted.journal
  features/data/journals/basic_folder/2020/08/29.txt
  features/data/journals/basic_folder/2020/08/31.txt
  features/data/journals/basic_folder/2020/09/24.txt
  features/data/journals/basic_onefile.journal
  features/data/journals/dayone_empty.dayone/entries/empty.txt
  features/data/journals/little_endian_dates.journal
  features/datetime.feature
  features/dayone.feature
  features/dayone_regressions.feature
  features/delete.feature
  features/encrypt.feature
  features/encryption.feature
  features/environment.py
  features/exporting.feature
  features/file_storage.feature
  features/folder.feature
  features/format.feature
  features/import.feature
  features/multiple_journals.feature
  features/password.feature
  features/regression.feature
  features/search.feature
  features/star.feature
  features/starring.feature
  features/steps/core.py
  features/steps/export_steps.py
  features/tag.feature
  features/tagging.feature
  features/upgrade.feature
  features/write.feature
Labels: build

#1032 Documentation updates
  README.md
  docs/encryption.md
  docs/export.md
  docs/formats.md
  docs/installation.md
  docs/overview.md
  docs/privacy-and-security.md
  docs/recipes.md
  docs/security.md
  docs/usage.md
  mkdocs.yml
Labels: documentation

#1063 Add circle ci config file for linux tests
  .circleci/config.yml
Labels: build

#1067 Add accessibility testing for docs site (http://jrnl.sh)
  .circleci/config.yml
  .circleci/pa11y.sh
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: build
