Repository jrnl-org/jrnl, pull requests merged in 2020-03, with the labels that each got.

#879 Update url for "beautiful timeline" in export.md
  docs/export.md
Labels: documentation

#698 Add --delete for interactive removal of entries
  features/core.feature
  features/data/configs/deletion.yaml
  features/data/journals/deletion.journal
  jrnl/Journal.py
  jrnl/cli.py
Labels: enhancement

#871 Update travis caching to speed up builds
  .travis.yml
Labels: build

#885 Update and reorganize CONTRIBUTING
  CONTRIBUTING.md
Labels: documentation
