Repository jrnl-org/jrnl, pull requests merged in 2021-01, with the labels that each got.

#1135 Fix broken search bar in docs site
  .github/workflows/docs.yaml
  docs_theme/assets/colors.css
  docs_theme/assets/theme.css
  docs_theme/main.html
  docs_theme/search.html
Labels: documentation

#1139 Allow custom extensions when editing (for easier syntax highlighting)
  features/data/configs/editor_markdown_extension.yaml
  features/data/templates/extension.md
  features/file_storage.feature
  features/steps/core.py
  jrnl/editor.py
Labels: enhancement

#1138 Fix keyring error handling
  features/password.feature
  features/steps/core.py
  jrnl/EncryptedJournal.py
Labels: bug

#1134 Notify user when config directory can't be created because there is already a file with the same name
  features/steps/core.py
  jrnl/cli.py
  jrnl/config.py
  jrnl/exception.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/output.py
  tests/test_exception.py
Labels: bug

#1148 Emphasize installing dependencies before testing
  CONTRIBUTING.md
Labels: documentation

#1137 Clarify installation documentation (#1097)
  docs/installation.md
Labels: documentation

#1146 Add new date format (`--format date`) for heatmapping
  features/format.feature
  jrnl/plugins/__init__.py
  jrnl/plugins/dates_exporter.py
Labels: enhancement

#1145 Add new `-today-in-history`, `-month`, `-day`, and `-year` search filters
  features/search.feature
  features/steps/core.py
  jrnl/Journal.py
  jrnl/args.py
  jrnl/jrnl.py
  tests/test_parse_args.py
Labels: enhancement

#1153 Fix OS compatibility issues for editors with spaces, slashes, and quotes
  features/environment.py
  features/steps/core.py
  features/steps/export_steps.py
  jrnl/color.py
  jrnl/editor.py
  jrnl/os_compat.py
  tests/test_os_compat.py
Labels: bug

#1154 Fix homebrew release, add options for release pipeline
  .github/workflows/release.yaml
Labels: build

#1160 Clarify editor documentation for PATH variable and VS Code
  docs/recipes.md
Labels: documentation

#1164 Make journal selection behavior more consistent when there's a colon with no date
  features/multiple_journals.feature
  jrnl/config.py
Labels: bug
