Repository jrnl-org/jrnl, pull requests merged in 2021-03, with the labels that each got.

#1177 Fix bug that prevented --format pretty and --format short from working
  features/format.feature
  features/steps/core.py
  features/steps/export_steps.py
  jrnl/jrnl.py
  jrnl/plugins/__init__.py
  tests/test_color.py
  tests/test_display.py
Labels: bug

#1211 Fix broken brew release process
  .github/workflows/release.yaml
Labels: build

#1220 Docs: Add emacs as external editor to recipes
  docs/recipes.md
Labels: documentation
