Repository jrnl-org/jrnl, pull requests merged in 2021-11, with the labels that each got.

#1365 Support pytest-bdd 5.x
  tests/lib/then_steps.py
Labels: test

#1290 Add --config-file argument to use alternate config file at runtime
  docs/advanced.md
  jrnl/args.py
  jrnl/config.py
  jrnl/install.py
  jrnl/jrnl.py
  tests/bdd/features/config_file.feature
  tests/bdd/test_features.py
  tests/lib/given_steps.py
  tests/unit/test_config_file.py
  tests/unit/test_parse_args.py
Labels: enhancement

#1362 Use Python 3.10 stable in CI
  .github/workflows/testing.yaml
  poetry.lock
  pyproject.toml
Labels: build

#1373 Use full Python version for GitHub Actions cache key
  .github/workflows/testing.yaml
Labels: build

#1366 Add added option to _print_edited_summary
  jrnl/jrnl.py
  tests/bdd/features/write.feature
Labels: bug
