Repository jrnl-org/jrnl, pull requests merged in 2022-10, with the labels that each got.

#1604 Update `.gitignore`
  .gitignore
Labels: build

#1594 Change default config to use journal key
  jrnl/config.py
  jrnl/install.py
  tests/lib/then_steps.py
Labels: bug

#1618 Remove wrong option in configuration file reference
  docs/reference-config-file.md
Labels: documentation

#1621 Fix bug for new `--list --format` options when no default journal is specified
  jrnl/Journal.py
  jrnl/commands.py
  jrnl/config.py
  jrnl/messages/MsgText.py
  tests/bdd/features/config_file.feature
  tests/bdd/features/format.feature
  tests/bdd/features/multiple_journals.feature
  tests/data/configs/no_default_journal.yaml
Labels: bug

#1625 Replace `flake8` with `flakeheaven` in linting steps
  docs/encryption.md
  poetry.lock
  pyproject.toml
Labels: test

#1611 Drop Python 3.9 and use Python 3.11 official release
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/testing_prs.yaml
  .github/workflows/testing_schedule.yaml
  docs/installation.md
  poetry.lock
  pyproject.toml
Labels: deprecated, packaging

#1626 Add double encryption test
  tests/bdd/features/encrypt.feature
Labels: test

#1628 Move existing linting into `flakeheaven`
  docs/encryption.md
  poetry.lock
  pyproject.toml
Labels: test
