Repository jrnl-org/jrnl, pull requests merged in 2022-09, with the labels that each got.

#1563 Add hint for how to get vi to go to end-of-file
  docs/tips-and-tricks.md
Labels: documentation

#1587 Update to use renamed flag for `brew bump-formula-pr`
  .github/workflows/release.yaml
Labels: build

#1588 Fix Docs Accessibility Testing
  .github/workflows/docs.yaml
  .github/workflows/testing_prs.yaml
  tasks.py
Labels: build

#1591 Update YAML export description in docs
  docs/formats.md
Labels: documentation

#1592 Add machine readable --list output
  jrnl/args.py
  jrnl/commands.py
  jrnl/output.py
  tests/bdd/features/format.feature
  tests/lib/then_steps.py
Labels: enhancement
