Repository jrnl-org/jrnl, pull requests merged in 2022-08, with the labels that each got.

#1527 Export to file(s) when first line/title of an entry is very long
  jrnl/plugins/text_exporter.py
  tests/bdd/features/format.feature
  tests/lib/helpers.py
  tests/lib/then_steps.py
Labels: bug

#1554 Fix docs pipeline, make docs tests easier to run locally and on different OSes
  .github/workflows/docs.yaml
  .gitignore
  docs/contributing.md
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
  tasks.py
Labels: build

#1555 Add actionlint to testing pipelines
  .github/actionlint-matcher.json
  .github/workflows/changelog.yaml
  .github/workflows/docs.yaml
  .github/workflows/release.yaml
  .github/workflows/testing_pipelines.yaml
Labels: build

#1556 Reformat contributor appreciation on `--help` screen
  jrnl/args.py
Labels: documentation

#1565 Quick fix follow up for actionlint
  .github/workflows/release.yaml
Labels: build

#1524 Add message showing the number of search results
  jrnl/jrnl.py
  jrnl/messages/MsgText.py
  tests/bdd/features/search.feature
Labels: enhancement

#1561 Suppress "Entry added" message if using default journal
  jrnl/jrnl.py
  tests/bdd/features/datetime.feature
  tests/bdd/features/file_storage.feature
  tests/bdd/features/override.feature
  tests/bdd/features/search.feature
  tests/bdd/features/star.feature
  tests/bdd/features/write.feature
Labels: enhancement

#1566 Remove note in contributing docs about gh-pages branch that we no longer use
  docs/contributing.md
Labels: documentation
