Repository jrnl-org/jrnl, pull requests merged in 2022-11, with the labels that each got.

#1631 Fix bug where changelog is always slightly out of date on release tags
  .github/workflows/changelog.yaml
Labels: build

#1629 Add `type-checking` plugin to linting checks
  jrnl/exception.py
  jrnl/messages/Message.py
  jrnl/override.py
  poetry.lock
  pyproject.toml
Labels: test

#1614 Add type hints
  jrnl/DayOneJournal.py
  jrnl/Entry.py
  jrnl/FolderJournal.py
  jrnl/args.py
  jrnl/cli.py
  jrnl/color.py
  jrnl/config.py
  jrnl/editor.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/os_compat.py
  jrnl/output.py
  jrnl/override.py
  jrnl/path.py
  jrnl/plugins/__init__.py
  jrnl/plugins/dates_exporter.py
  jrnl/plugins/fancy_exporter.py
  jrnl/plugins/jrnl_importer.py
  jrnl/plugins/json_exporter.py
  jrnl/plugins/markdown_exporter.py
  jrnl/plugins/tag_exporter.py
  jrnl/plugins/text_exporter.py
  jrnl/plugins/util.py
  jrnl/plugins/xml_exporter.py
  jrnl/plugins/yaml_exporter.py
  jrnl/prompt.py
  jrnl/time.py
  jrnl/upgrade.py
Labels: build

#1630 Add `simplify` plugin to linting checks
  jrnl/DayOneJournal.py
  jrnl/EncryptedJournal.py
  jrnl/Journal.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/messages/__init__.py
  jrnl/plugins/markdown_exporter.py
  poetry.lock
  pyproject.toml
  tests/unit/test_parse_args.py
Labels: build, test

#1636 Remove Windows 7 known issue since Windows 7 is no longer supported
  docs/advanced.md
Labels: documentation

#1602 Rework Encryption to enable future support of other encryption methods
  jrnl/EncryptedJournal.py
  jrnl/Journal.py
  jrnl/cli.py
  jrnl/commands.py
  jrnl/encryption/BaseEncryption.py
  jrnl/encryption/BaseKeyEncryption.py
  jrnl/encryption/BasePasswordEncryption.py
  jrnl/encryption/Jrnlv1Encryption.py
  jrnl/encryption/Jrnlv2Encryption.py
  jrnl/encryption/NoEncryption.py
  jrnl/encryption/__init__.py
  jrnl/keyring.py
  jrnl/messages/MsgText.py
  jrnl/plugins/fancy_exporter.py
  jrnl/prompt.py
  jrnl/upgrade.py
  tests/bdd/features/encrypt.feature
  tests/lib/given_steps.py
  tests/lib/when_steps.py
Labels: bug, enhancement
