Repository jrnl-org/jrnl, pull requests merged in 2022-06, with the labels that each got.

#1490 `-not` search parameter no longer opens editor
  jrnl/jrnl.py
  tests/bdd/features/search.feature
Labels: bug

#1492 Create folder if config ends with (back)slash
  docs/journal-types.md
  jrnl/Journal.py
  tests/bdd/features/file_storage.feature
  tests/data/configs/missing_directory.yaml
  tests/lib/then_steps.py
Labels: bug

#1495 Fixed error related to display_format in config file for some values
  jrnl/jrnl.py
  tests/bdd/features/format.feature
  tests/unit/test_display.py
  tests/unit/test_jrnl.py
Labels: bug

#1475 Rework how all output and messaging works in jrnl
  jrnl/EncryptedJournal.py
  jrnl/FolderJournal.py
  jrnl/Journal.py
  jrnl/cli.py
  jrnl/color.py
  jrnl/commands.py
  jrnl/config.py
  jrnl/editor.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/messages.py
  jrnl/messages/Message.py
  jrnl/messages/MsgStyle.py
  jrnl/messages/MsgText.py
  jrnl/messages/__init__.py
  jrnl/output.py
  jrnl/plugins/fancy_exporter.py
  jrnl/plugins/jrnl_importer.py
  jrnl/plugins/markdown_exporter.py
  jrnl/plugins/text_exporter.py
  jrnl/plugins/yaml_exporter.py
  jrnl/prompt.py
  jrnl/upgrade.py
  pyproject.toml
  tests/bdd/features/config_file.feature
  tests/bdd/features/datetime.feature
  tests/bdd/features/encrypt.feature
  tests/bdd/features/format.feature
  tests/bdd/features/multiple_journals.feature
  tests/bdd/features/override.feature
  tests/bdd/features/star.feature
  tests/bdd/features/upgrade.feature
  tests/bdd/features/write.feature
  tests/lib/fixtures.py
  tests/lib/given_steps.py
  tests/lib/then_steps.py
  tests/lib/when_steps.py
  tests/unit/test_output.py
Labels: enhancement

#1500 Add Python 3.11 to PR tests
  .github/workflows/testing_prs.yaml
Labels: build

#1503 Replace `make` with python alternative (`poe`)
  .github/PULL_REQUEST_TEMPLATE.md
  Makefile
  docs/contributing.md
  poetry.lock
  pyproject.toml
Labels: build

#1505 Fix Poetry caching for accessibility tests
  .github/workflows/docs.yaml
Labels: build

#1506 Stop hardcoding bot info in changelog pipeline
  .github/workflows/changelog.yaml
Labels: build

#1504 Implement Tox for testing
  .github/actions/run_tests/action.yaml
  .github/workflows/docs.yaml
  .gitignore
  poetry.lock
  pyproject.toml
  tests/__init__.py
Labels: build

#1510 Display message when no edits take place
  jrnl/editor.py
  jrnl/jrnl.py
  jrnl/messages/MsgText.py
Labels: bug

#1518 Reduce difference between local and CI environments
  .github/actions/run_tests/action.yaml
  pyproject.toml
Labels: build

#1513 Add bdd tests for jrnl installation
  tests/bdd/features/install.feature
  tests/bdd/test_features.py
  tests/lib/fixtures.py
  tests/lib/given_steps.py
  tests/lib/then_steps.py
  tests/lib/when_steps.py
Labels: build

#1519 Run tests in parallel
  poetry.lock
  pyproject.toml
Labels: test

#1520 Add and run `isort` on Python files
  jrnl/DayOneJournal.py
  jrnl/EncryptedJournal.py
  jrnl/Entry.py
  jrnl/FolderJournal.py
  jrnl/Journal.py
  jrnl/__init__.py
  jrnl/__main__.py
  jrnl/args.py
  jrnl/cli.py
  jrnl/color.py
  jrnl/commands.py
  jrnl/config.py
  jrnl/editor.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/messages/Message.py
  jrnl/messages/MsgStyle.py
  jrnl/messages/__init__.py
  jrnl/output.py
  jrnl/override.py
  jrnl/plugins/__init__.py
  jrnl/plugins/dates_exporter.py
  jrnl/plugins/fancy_exporter.py
  jrnl/plugins/jrnl_importer.py
  jrnl/plugins/json_exporter.py
  jrnl/plugins/markdown_exporter.py
  jrnl/plugins/tag_exporter.py
  jrnl/plugins/text_exporter.py
  jrnl/plugins/xml_exporter.py
  jrnl/plugins/yaml_exporter.py
  jrnl/prompt.py
  jrnl/upgrade.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/lib/fixtures.py
  tests/lib/given_steps.py
  tests/lib/then_steps.py
  tests/lib/when_steps.py
  tests/unit/test_color.py
  tests/unit/test_config_file.py
  tests/unit/test_jrnl.py
  tests/unit/test_override.py
  tests/unit/test_path.py
Labels: test
