Repository jrnl-org/jrnl, pull requests merged in 2022-05, with the labels that each got.

#1449 Yaml export errors now don't show stack trace
  jrnl/plugins/text_exporter.py
  jrnl/plugins/yaml_exporter.py
  tests/bdd/features/format.feature
Labels: bug

#1461 Give a proper message when trying to use an empty config file
  jrnl/install.py
  tests/bdd/features/config_file.feature
  tests/data/configs/empty_file.yaml
  tests/lib/given_steps.py
Labels: bug

#1466 The `-not` option with no arguments now outputs error instead of stack trace
  jrnl/args.py
  tests/unit/test_parse_args.py
Labels: bug

#1452 Implement --change-time flag
  jrnl/FolderJournal.py
  jrnl/Journal.py
  jrnl/args.py
  jrnl/jrnl.py
  jrnl/messages.py
  tests/bdd/features/change_time.feature
  tests/bdd/test_features.py
  tests/unit/test_parse_args.py
Labels: enhancement

#1478 Show name of journal when creating a password/encrypting
  jrnl/prompt.py
Labels: enhancement

#1468 Always expand all paths (journals, templates, etc)
  jrnl/Journal.py
  jrnl/config.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/path.py
  jrnl/upgrade.py
  pyproject.toml
  tests/conftest.py
  tests/unit/test_path.py
Labels: bug

#1477 Prompt for password change when using 'jrnl --encrypt' on already encrypted journal
  jrnl/commands.py
  tests/bdd/features/encrypt.feature
Labels: bug

#1471 Document --change-time in web-based docs' command line reference
  docs/reference-command-line.md
  docs_theme/requirements.txt
  poetry.lock
  pyproject.toml
Labels: documentation
