Repository jrnl-org/jrnl, pull requests merged in 2022-03, with the labels that each got.

#1423 Fix tests for daylight savings
  tests/bdd/features/datetime.feature
  tests/bdd/features/search.feature
Labels: test

#1416 Replace PyYAML with ruamel.yaml
  jrnl/config.py
  jrnl/plugins/template.py
  poetry.lock
  pyproject.toml
  tests/data/configs/editor_markdown_extension.yaml
  tests/lib/then_steps.py
Labels: build

#1424 Reformat additional messages and finish centralizing exception handling
  jrnl/EncryptedJournal.py
  jrnl/Journal.py
  jrnl/cli.py
  jrnl/config.py
  jrnl/editor.py
  jrnl/exception.py
  jrnl/install.py
  jrnl/jrnl.py
  jrnl/messages.py
  jrnl/output.py
  jrnl/plugins/jrnl_importer.py
  jrnl/upgrade.py
  tests/bdd/features/delete.feature
  tests/bdd/features/write.feature
  tests/unit/test_config_file.py
  tests/unit/test_export.py
Labels: enhancement

#1439 Pin jinja2 in docs requirements to keep readthedocs builds from failing
  docs_theme/requirements.txt
  readthedocs.yml
Labels: build
