Repository jrnl-org/jrnl, pull requests merged in 2022-07, with the labels that each got.

#1536 Pin `pytest-bdd` to <6.0 to temporarily avoid breaking changes
  poetry.lock
  pyproject.toml
Labels: build

#1540 Disable gherkin reporter to fix test suite
  pyproject.toml
Labels: test

#1522 Fixed index out of range error in fancy exporter
  jrnl/plugins/fancy_exporter.py
Labels: bug

#1507 Add linewrap option 'auto'
  docs/reference-config-file.md
  jrnl/Entry.py
  jrnl/plugins/fancy_exporter.py
  tests/bdd/features/config_file.feature
  tests/data/configs/linewrap_auto.yaml
Labels: enhancement
