Repository jrnl-org/jrnl, pull requests merged in 2023-03, with the labels that each got.

#1698 Update documentation front page text
  docs_theme/index.html
Labels: documentation

#1685 Use pytest-bdd 6
  jrnl/journals/Journal.py
  poetry.lock
  pyproject.toml
  tests/bdd/features/change_time.feature
  tests/bdd/features/search.feature
  tests/lib/fixtures.py
  tests/lib/given_steps.py
  tests/lib/helpers.py
  tests/lib/then_steps.py
  tests/lib/type_builders.py
  tests/lib/when_steps.py
Labels: test, dependencies

#1695 Add message with config location and docs location when installation is complete
  jrnl/install.py
  jrnl/messages/MsgText.py
  tests/bdd/features/install.feature
Labels: enhancement

#1684 Document `-tagged`, `-not -tagged`, and `-not -starred`
  docs/reference-command-line.md
Labels: documentation

#1667 Add ability to use template with `--template`
  docs/tips-and-tricks.md
  jrnl/args.py
  jrnl/config.py
  jrnl/controller.py
  jrnl/journals/Journal.py
  jrnl/messages/MsgText.py
  jrnl/override.py
  tests/bdd/features/template.feature
  tests/lib/fixtures.py
  tests/lib/given_steps.py
  tests/lib/then_steps.py
  tests/unit/test_parse_args.py
Labels: enhancement

#1669 Allow combinations of `--change-time`, `--delete`, and `--edit` while correctly counting the number of entries affected
  jrnl/controller.py
  jrnl/editor.py
  jrnl/exception.py
  jrnl/journals/FolderJournal.py
  jrnl/journals/Journal.py
  jrnl/messages/MsgText.py
  tests/bdd/features/actions.feature
  tests/bdd/features/change_time.feature
  tests/bdd/features/delete.feature
  tests/bdd/features/search.feature
  tests/bdd/features/write.feature
  tests/bdd/test_features.py
  tests/lib/given_steps.py
  tests/lib/then_steps.py
  tests/unit/test_controller.py
  tests/unit/test_export.py
  tests/unit/test_override.py
  tests/unit/test_parse_args.py
Labels: bug
