Repository jrnl-org/jrnl, pull requests merged in 2023-01, with the labels that each got.

#1646 Update version key in config file after version changes
  jrnl/install.py
  tests/bdd/features/config_file.feature
Labels: bug

#1648 Add tag to XML file when edited DayOne entry and is searchable afterward
  jrnl/DayOneJournal.py
  tests/bdd/features/write.feature
Labels: bug

#1659 Add basic template test
  tests/bdd/features/template.feature
  tests/bdd/test_features.py
  tests/data/templates/basic.template
  tests/lib/given_steps.py
Labels: test

#1655 Fix markup in "Advanced Usage" doc
  docs/advanced.md
Labels: documentation

#1657 Update docs to include time and title in arguments with `--edit`
  docs/external-editors.md
Labels: documentation

#1642 Add more type hints
  jrnl/Entry.py
  jrnl/Journal.py
  jrnl/commands.py
  jrnl/encryption/__init__.py
  jrnl/keyring.py
Labels: enhancement

#1662 Refactor flow for easier access to some files (avoid things like `jrnl.Journal.Journal` and `jrnl.jrnl` co-existing)
  jrnl/__main__.py
  jrnl/color.py
  jrnl/commands.py
  jrnl/controller.py
  jrnl/install.py
  jrnl/journals/DayOneJournal.py
  jrnl/journals/Entry.py
  jrnl/journals/FolderJournal.py
  jrnl/journals/Journal.py
  jrnl/journals/__init__.py
  jrnl/main.py
  jrnl/plugins/dates_exporter.py
  jrnl/plugins/fancy_exporter.py
  jrnl/plugins/jrnl_importer.py
  jrnl/plugins/json_exporter.py
  jrnl/plugins/markdown_exporter.py
  jrnl/plugins/tag_exporter.py
  jrnl/plugins/text_exporter.py
  jrnl/plugins/util.py
  jrnl/plugins/xml_exporter.py
  jrnl/plugins/yaml_exporter.py
  jrnl/upgrade.py
  pyproject.toml
  tests/lib/fixtures.py
  tests/lib/when_steps.py
  tests/unit/test_controller.py
Labels: enhancement

#1663 Search for entries with no tags or stars with `-not -starred` and `-not -tagged`
  jrnl/args.py
  jrnl/controller.py
  jrnl/journals/Journal.py
  tests/bdd/features/search.feature
  tests/unit/test_parse_args.py
Labels: enhancement
