Repository jrnl-org/jrnl, pull requests merged in 2023-02, with the labels that each got.

#1673 Update documentation on temporary files naming
  docs/privacy-and-security.md
Labels: documentation

#1653 Don't save templated journal entries if the received raw text is the same as the template itself
  jrnl/controller.py
  jrnl/messages/MsgText.py
  tests/bdd/features/template.feature
Labels: bug

#1680 Update documentation about privacy and security in VSCode
  docs/privacy-and-security.md
Labels: documentation

#1686 Document temporary file extension behavior when using template
  docs/privacy-and-security.md
  docs/reference-config-file.md
Labels: documentation

#1691 Support mkdocs 1.4.2 and fix its missing breadcrumb
  docs_theme/assets/theme.css
  docs_theme/breadcrumbs.html
  docs_theme/requirements.txt
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation, dependencies

#1690 Save empty journal on install instead of just creating a zero-length file
  jrnl/journals/Journal.py
  tests/bdd/features/install.feature
Labels: bug

#1687 Prompt to include colors in config when first running jrnl
  jrnl/config.py
  jrnl/install.py
  jrnl/messages/MsgText.py
  poetry.lock
  tests/bdd/features/file_storage.feature
  tests/bdd/features/install.feature
Labels: enhancement
